baseURL = 'https://webgptorg.github.io/the-book-docs/'
languageCode = 'en-us'
title = 'The Promptbook Project documentation'
theme = "hugo-book"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


